name: Deploy to Server

on:
  # Manual deployment only
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Bot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            # Navigate to project directory
            PROJECT_PATH="${{ secrets.PROJECT_PATH }}"
            if [ -z "$PROJECT_PATH" ]; then
              PROJECT_PATH="$HOME/telegram-bot"
            fi
            cd "$PROJECT_PATH"

            # Pull latest changes
            git pull origin main 2>/dev/null || git pull origin master

            # Stop running container
            docker compose down

            # Rebuild and start container
            docker compose up -d --build

            # Clean up old images
            docker image prune -f

            # Show status
            docker compose ps
            docker compose logs --tail=50 bot

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
