name: Deploy to Server

on:
  # Manual deployment only
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Bot
    runs-on: ubuntu-latest
    # Only run if secrets are configured
    if: ${{ secrets.SERVER_HOST != '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            # Navigate to project directory
            cd ${{ secrets.PROJECT_PATH || '~/telegram-bot' }}

            # Pull latest changes
            git pull origin main || git pull origin master

            # Stop running container
            docker-compose down

            # Rebuild and start container
            docker-compose up -d --build

            # Clean up old images
            docker image prune -f

            # Show status
            docker-compose ps
            docker-compose logs --tail=50 bot

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi
